name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t lesson-aws:latest .
          docker tag lesson-aws:latest ${{ secrets.AWS_REGISTRY_URL }}/lesson-aws:latest
          docker push ${{ secrets.AWS_REGISTRY_URL }}/lesson-aws:latest

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster lesson-aws --service lesson-aws-service --force-new-deployment
